var namespace_sad_pumpkin_1_1_util_1_1_combat_engine_1_1_requirement_calculators =
[
    [ "IRequirementCalc", "interface_sad_pumpkin_1_1_util_1_1_combat_engine_1_1_requirement_calculators_1_1_i_requirement_calc.html", "interface_sad_pumpkin_1_1_util_1_1_combat_engine_1_1_requirement_calculators_1_1_i_requirement_calc" ],
    [ "NoRequirements", "class_sad_pumpkin_1_1_util_1_1_combat_engine_1_1_requirement_calculators_1_1_no_requirements.html", "class_sad_pumpkin_1_1_util_1_1_combat_engine_1_1_requirement_calculators_1_1_no_requirements" ]
];